### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by mdiin** [niwibe/clojure.jdbc-c3p0#1]
Hi. It seems like the github pages documentation that is referred to in the README is no longer available.

**Comment by niwinz** [comment]
Sorry, I will update it with the new documentation link!

**Comment by niwinz** [comment]
Now, the documentation is entirely available in a readme, and released a new version that makes it compatible with both versions of clojure.jdbc (0.3.x and 0.4.x).

**Comment by mdiin** [comment]
Nice! Great job on the library!

**Comment by niwinz** [comment]
Thanks!
