### ISSUE TITLE
Oracle connection string won't work

### ISSUE THREAD

**Issue by blkt** [niwibe/clojure.jdbc-c3p0#3]
Hi,

executing the following fails

`(p/make-datasource-spec "jdbc:oracle:thin:scott/tiger@myhost:1521:orcl")
java.lang.ClassCastException: java.lang.String cannot be cast to java.net.URI`

The example connection string is taken [here](https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html).

Regards

**Comment by bostonaholic** [comment]
@blkt try this instead

```
(pool/make-datasource-spec
  {:subprotocol "jdbc:oracle:thin:scott/tiger"
   :subname "//myhost:1521:orcl"})
```

**Comment by samsondav** [comment]
Thanks @bostonaholic .

**Comment by bostonaholic** [comment]
No problem!
